### ISSUE TITLE
Implement REST Endpoint for saving and fetching data

### ISSUE THREAD

**Issue by mikehenrty** [jdinartejesus/guitar-star#5]
Maybe GET /users
and POST /user (with some data in the post body for name)

Write a test that GETs users, and makes sure none are there, then POST a new user, then GET users again and make sure the user you POSTed is returned.

**Comment by jdinartejesus** [comment]
@mikehenrty uau I needed a month for implementing this. please take a look on it Michael.
Maybe needs some refactoring but is working!

**Comment by mikehenrty** [comment]
Looking good buddy! I left some comments on that commit: https://github.com/jdinartejesus/guitar-star/commit/d96a93efcd476dbe0b46a2a23f18c36950f6f831

In general it's better to send a PR, and have me review that rather than a commit to a branch (`develop` in this case). This is the workflow built into github, and things may get confusing to track if we don't do it that way.

And of course, I'd love to see some TESTS! 😃
